source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'

gem 'sinatra'
gem 'sqlite3'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake', '>=2.0.5'
gem 'tux'
gem 'rspec'
gem 'rack-test'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'require_all'